[[albums]]
name = "madrid"
pubDate = "2025-08-18"

[[albums]]
name = "barcelona"
pubDate = "2024-12-14"

[[albums]]
name = "valencia"
pubDate = "2024-12-18"

[[albums]]
name = "lisboa"
pubDate = "2023-08-20"

[[albums]]
name = "cacilhas"
pubDate = "2023-07-09"

# [[albums]]
# name = "sintra"
# pubDate = "2024-06-20"

# [[albums]]
# name = "sines"
# pubDate = "2024-06-20"
